version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume-project"
s3_bucket = "mydevops-resume-website"
s3_prefix = "cloud-resume-project"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
